import * as fs from 'node:fs';
import * as path from 'node:path';
export async function writeReport(opts) {
    fs.mkdirSync(opts.reportsRoot, { recursive: true });
    const fileName = `report-${opts.ts}.md`;
    const filePath = path.join(opts.reportsRoot, fileName);
    const content = `# DSH Web Crash Report — ${opts.ts}

**Action:** ${opts.action}

## Health Snapshot

- up: ${opts.health.up}
- httpCode: ${opts.health.httpCode ?? 'n/a'}
- error: ${opts.health.error ?? 'none'}
- degraded: ${opts.health.degraded ?? false}

## Git Diff (link plugins)

\`\`\`diff
${opts.gitDiff || '(no changes)'}
\`\`\`

## Log Tail (last 200 lines)

\`\`\`
${opts.logTail.slice(-5000) || '(empty)'}
\`\`\`

## Next Steps

- Check \`~/.dsh/.supervisor/lkg/\` for last-known-good
- Review \`failed/${opts.ts}/\` snapshot
- If degraded, fix the listed plugin row and run \`pnpm verify\` + dry-boot

---
*Generated by dsh-web-supervisor*
`;
    fs.writeFileSync(filePath, content);
    return filePath;
}
export async function collectGitDiff(workspaceRoot) {
    try {
        const { execSync } = await import('node:child_process');
        // Find all link: plugins from profiles
        const out = execSync('git -C ' + JSON.stringify(workspaceRoot) + ' status --porcelain 2>/dev/null || true', { encoding: 'utf-8' });
        if (out.trim()) {
            const diff = execSync('git -C ' + JSON.stringify(workspaceRoot) + ' diff 2>/dev/null | head -n 200', { encoding: 'utf-8' });
            return diff || out;
        }
        return '';
    }
    catch {
        return '';
    }
}
